export type TImageAssetName = 
     '100%pr' | 
     'aboutTheAdvertisement' | 
     'checkedAdvertisementMethods' | 
     'doOrDie' | 
     'myLifeInAdvertisement' | 
     'newMarketingRules' | 
     'ogilvy' | 
     'prOnTheHighLevel' | 
     'publicRelations' | 
     'strategicCommunication' | 
     'favicon' | 
     'bonuses' | 
     'booksToRead' | 
     'classics' | 
     'clocks' | 
     'contacts' | 
     'goodIdea' | 
     'graduators' | 
     'guitar' | 
     'notes' | 
     'ourOffice' | 
     'readingMaterial' | 
     'schedule' | 
     'travelling' | 
     'workingProcess' | 
     'writingMachine' | 
     'allaShorina' | 
     'juliaBrikShorina' | 
     'juliaBrikShorina2' | 
     'kudelya' | 
     'maria' | 
     'nataliaGusak' | 
     'nataliaMagdaBrikShorina' | 
     'stanislav' | 
     'storozhenko' | 
     'tsibulyaGusak' | 
     'verngeslyaukayte';